apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-repo-creds
  namespace: argocd
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore # <--- ZMIANA: Wskazujemy na globalny store
  target:
    name: k8s-repo
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        insecure: "false"
        enableLfs: "true"
  data:
  - secretKey: url
    remoteRef:
      key: argocd/repo-credentials
      property: url
  - secretKey: sshPrivateKey
    remoteRef:
      key: argocd/repo-credentials
      property: sshPrivateKey