apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: k8s-repo
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        insecure: "false"
        enableLfs: "true"
  
  # ▼▼▼ TO JEST TO SAMO CO W WIDEO (Minuta 19:37) ▼▼▼
  # Skoro na screenie masz Key/Value, to 'extract' pobierze je automatycznie.
  dataFrom:
  - extract:
      key: argocd/repo-credentials