apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1m # Ustawiłem na 1 minutę dla szybszych testów
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: k8s-repo
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        insecure: "false"
        enableLfs: "true"
  
  # ▼▼▼ ZMIANA: Używamy dataFrom zamiast data ▼▼▼
  # To naprawia problem "pustych pól" i pobiera cały JSON jak leci.
  dataFrom:
  - extract:
      key: argocd/repo-credentials