apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-repo-creds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: k8s-repo
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  dataFrom:
  - extract:
      key: argocd/repo-credentials