# plik: argocd/apps/external-secrets-operator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    # Ważne: Wave -1 sprawi, że ten Operator zainstaluje się PIERWSZY
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13 # Zalecam pinowanie wersji!
    helm:
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets # Dobra praktyka: osobny namespace dla operatora
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true