# plik: argocd/apps/main-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd
  annotations:
    # Wave 0 (lub wyższy) sprawi, że to uruchomi się PO operatorze (Wave -1)
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/k-napiontek/my-app.git
    targetRevision: main
    path: argocd/infra-config # Wskazujemy na nowy folder z kroku 2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true