apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "81.4.2"
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      values: |
        prometheus:
          prometheusSpec:
            retention: 15d
            retentionSize: 45GB
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
        grafana:
          persistence:
            enabled: true
            size: 5Gi
        alertmanager:
          alertmanagerSpec:
            retention: 120h
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true