apiVersion: external-secrets.io/v1
kind: ClusterSecretStore  # <--- ZMIANA: Globalny Store
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets # <--- TERAZ MOŻEMY WSKAZAĆ GDZIE ON JEST